// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixjnngqtnqpqfujslxbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4am5uZ3F0bnFwcWZ1anNseGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTM4NzIsImV4cCI6MjA2MjU2OTg3Mn0.JusyUK-GbCa7hNVdjbuxaNZyfStMynmrRWqCW8ROy3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);